### PR TITLE
Add support for ReactiveForms

### PR DESCRIPTION
**Pull request by naeramarth7**
This PR adds support for forms build using the `ReactiveFormsModule`.  
By now, the `nouislider` component relies on the `ngModel` property to be set - which can not be used in conjunction with `[formGroup]`s.

### CODE REVIEW

**Comment by naeramarth7** [comment]
Apparently, I also had to add tooltips on my branch - which updated the PR. Let me know, if you should remove that part for this PR.

**Comment by tb** [comment]
@naeramarth7 could you please add a test that verifies reactive forms integration works?

**Comment by naeramarth7** [comment]
@tb Should be sufficient? (:

**Comment by tb** [comment]
@naeramarth7 thank you, its now merged and published to npm

**Pull request merged**
