### PR TITLE
Fix formatter

### PR DESCRIPTION
**Pull request by gmazzamuto**
Following the discussion in PR #42, here is my proposed solution to the new problem.

@ryan-morris I have also included a working example with a time formatter
@tb I think you should remove the .js and the .d.ts files from the repo, since they are generated by the build process. They only make stashes, diffs, merges etc more complicated :)

### CODE REVIEW

**Comment by ryan-morris** [comment]
I think this should work. Similar to what I was looking at doing [here](https://github.com/devenvy/ng2-nouislider/commit/774a58d7f3ede1d9436dee4acbd3c670785e8693) , moving toValue to the class and having it utilize the formatter.

**Comment by tb** [comment]
@gmazzamuto Thanks! I will remove the .js and .d.ts files

I have published the aot branch as "ng2-nouislider@1.5.0-beta1" can you please check it, let me know if I should publish it as 1.5.0

**Comment by gmazzamuto** [comment]
Perhaps this can be useful. From npm documentation:
> If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.

In the end, I think that only `nouislider.js` and `README.md` should go in the package. Just these two files, not even the demo folder.

version 1.5.0-beta2 is broken: there are no compiled files in it.

I haven't tried version 1.5.0-beta1 from the npm repository, because I have upgraded to angular 2.4 and it doesn't work without aot. But I have tried it from the git repository, and it seems to work properly in my project. Unfortunately I have found another little bug, see #54. Please consider that for the next release!

**Comment by tb** [comment]
@gmazzamuto Yes, beta2 was my test to check if the git ignored files will be included - it did not work. Can you try "ng2-nouislider@1.5.0-beta1"? This is without the gitignore so it should work.

**Comment by gmazzamuto** [comment]
@tb I tried ng2-nouislider@1.5.0-beta4 and it works!

Speaking of PR #54, I forgot to mention that it is a fix for this PR (#52).

**Comment by ryan-morris** [comment]
I'm not seeing these changes reflected in `1.5.0-beta4`. The version in node_modules has the `1.5.0-beta4` version number but still contains the older `toValue` method. Do I need to test against the `tb:aot` branch?

**Comment by tb** [comment]
I published now ng2-nouislider@1.5.0-beta5 that includes PR #54. If you are fine with it I will publish it as 1.5.0.

@gmazzamuto since you have contributed a lot to this project I will give you write access to repo and npm.

**Comment by ryan-morris** [comment]
tried beta5, everything looks good to me

**Comment by tb** [comment]
1.5.0 has been published

**Comment by gmazzamuto** [comment]
@tb thanks!

**Pull request merged**
