### PR TITLE
build: use ng-packagr for bundling the library

### PR DESCRIPTION
**Pull request by mattlewis92**
I was trying out our app with the new ivy compiler and this package wasn't working with it because it wasn't in the angular package format, this refactors all the build process to use ng-packagr which nicely takes care of all the hard work. Thanks for your work on this library! 😄

### CODE REVIEW

**Comment by tb** [comment]
Thanks @mattlewis92! I published new package as 1.8.0

**Comment by mattlewis92** [comment]
Nice one, thank you! 😊

**Comment by mattlewis92** [comment]
Oh damn, looks like that didn't work, when you publish you need to do `npm publish dist` to only publish the dist folder

**Comment by thekuzia** [comment]
Hi guys, looks like version **1.8.0** broke your package, plz look!

**Comment by willyboy** [comment]
@thekuzia You can import as ng2-nouislider/dist until the package is republished.

**Comment by tb** [comment]
I published 1.8.1 with `npm publish dist` now.

**Comment by mattlewis92** [comment]
This should do the trick! https://github.com/tb/ng2-nouislider/pull/214

**Comment by mattlewis92** [comment]
This should do the trick! https://github.com/tb/ng2-nouislider/pull/211

**Comment by mattlewis92** [comment]
Fix here: https://github.com/tb/ng2-nouislider/pull/211

**Comment by mattlewis92** [comment]
Sorry my bad, will send a PR shortly with a fix 😄

**Pull request merged**
